INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (7, 'Antártida');
INSERT INTO regiones (id, nombre) VALUES (8, 'Africa');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1,'Fernando', 'de la Calle', 'fernando@gmail.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, 'Sergio', 'de la Calle', 'Sergio@gmail.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5, 'Roberto', 'de la Calle', 'Roberto@gmail.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5, 'Mariano', 'de la Calle', 'Mariano@gmail.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, 'Rodrigo', 'de la Calle', 'Rodrigo@gmail.com', '2018-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8, 'Jorge', 'de la Calle', 'Jorge@gmail.com', '2018-01-01');